name: Hello World
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: LS
        run: 'ls'
      - name: Print Hello World
        run: 'echo "Hello World"'
